### ISSUE TITLE
Tie button causes Reference Error

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#116]
I clicked the Tie button from the search result shown, resulting in (https://test.polomoto.com/participants/tie/61adb91a-20b8-4184-9e4a-bd8ae334a3a7)

ReferenceError: /usr/src/event-manager/views/participants/tieParticipants.ejs:7
    5|   </head>
    6|   <body class="bg-gray">
 >> 7|     <%- include('../partials/header', {title: "Tie Participant"}) %>
    8|     <div class="container content">
    9|       <table id="participantsTable" class="table">
    10|         <thead>

/usr/src/event-manager/views/partials/header.ejs:7
    5| <div class="wrapper">
    6| 	<nav id="sidebar">
 >> 7| 		<% if(user) { %>
    8| 			<img src="<%= user.pictureURL %>" class="img-thumbnail rounded-circle">
    9| 			<p> <%= `${user.firstName} ${user.lastName}` %> </p>
    10| 		<% } %>

user is not defined
    at eval (/usr/src/event-manager/views/partials/header.ejs:12:8)
    at header (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:656:17)
    at include (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:654:39)
    at eval (/usr/src/event-manager/views/participants/tieParticipants.ejs:15:17)
    at tieParticipants (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:656:17)
    at tryHandleCache (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:459:10)
    at View.render (/usr/src/event-manager/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/src/event-manager/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/src/event-manager/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/src/event-manager/node_modules/express/lib/response.js:1012:7)
    at app.get (/usr/src/event-manager/server.js:292:7)

![image](https://user-images.githubusercontent.com/11206022/79685272-81105500-8205-11ea-92ab-dccdd64ab695.png)

**Comment by davidem00** [comment]
duplicate of #71
