### ISSUE TITLE
TypeError exception when selecting to participant History

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#132]
clicking the History View button on CJ's registration under the July Outing trip in the test system generates an exception.

Other participants do not generate an error.

TypeError: /usr/src/event-manager/views/participants/singleParticipant.ejs:4
    2| <html lang="en">
    3|   <head>
 >> 4|     <%- include('../partials/head', {title: participants[0].firstName + ' ' + participants[0].lastName}) %>
    5|   </head>
    6|   <body>
    7|     <%- include('../partials/header', {title: "All Participants"}) %>

Cannot read property 'firstName' of undefined
    at eval (/usr/src/event-manager/views/participants/singleParticipant.ejs:12:69)
    at singleParticipant (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:656:17)
    at tryHandleCache (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:459:10)
    at View.render (/usr/src/event-manager/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/src/event-manager/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/src/event-manager/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/src/event-manager/node_modules/express/lib/response.js:1012:7)
    at app.get (/usr/src/event-manager/server.js:272:7)

![image](https://user-images.githubusercontent.com/11206022/80254815-d4d9ce80-8649-11ea-8433-2fdc5cff3a22.png)

**Comment by PoLoMoTo** [comment]
I cannot reproduce this error as that participant is not in the database anymore and none of the current participants cause this error.  Please reopen this issue with a new participant if it occurs again.

**Comment by davidem00** [comment]
I wondered about that, but I thought I specifically refreshed the page, and it still showed (as opposed to leaving the page and returning).  I could be wrong, but I thought I had done so.

Does clicking the browser page Refresh button re-query the data in each of these grid pages?
