### ISSUE TITLE
TypeError exception in loginFailed retrieving image for invalid user

### ISSUE THREAD

**Issue by davidem00** [LICCB/event-manager#163]
user is undefined, but typeof check is not catching it, line 7 of header.ejs

TypeError: /usr/src/event-manager/views/loginFailed.ejs:7
    5|   </head>
    6|   <body class="bg-gray">
 >> 7|     <%- include('partials/header', {title: "Home", user: user}) %>
    8|     <div class="container content">
    9|       <p>There was a failure during your login attempt.</p>
    10|       <p>You either do not have an account with the LICCB or your account has been disabled.</p>

/usr/src/event-manager/views/partials/header.ejs:8
    6| 	<nav id="sidebar">
    7| 		<% if(typeof user !== "undefined") { %>
 >> 8| 			<img src="<%= user.pictureURL %>" class="img-thumbnail rounded-circle">
    9| 			<p> <%= `${user.firstName} ${user.lastName}` %> </p>
    10| 		<% } %>
    11|         <ul class="list-unstyled components">

Cannot read property 'pictureURL' of null
    at eval (/usr/src/event-manager/views/partials/header.ejs:15:31)
    at header (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:656:17)
    at include (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:654:39)
    at eval (/usr/src/event-manager/views/loginFailed.ejs:15:17)
    at loginFailed (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:656:17)
    at tryHandleCache (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/usr/src/event-manager/node_modules/ejs/lib/ejs.js:459:10)
    at View.render (/usr/src/event-manager/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/src/event-manager/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/src/event-manager/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/src/event-manager/node_modules/express/lib/response.js:1012:7)
    at app.get (/usr/src/event-manager/server.js:573:7)
    at Layer.handle [as handle_request] (/usr/src/event-manager/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/event-manager/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/event-manager/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/event-manager/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/event-manager/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/event-manager/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/event-manager/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/usr/src/event-manager/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at SessionStrategy.authenticate (/usr/src/event-manager/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/usr/src/event-manager/node_modules/passport/lib/middleware/authenticate.js:366:16)

**Comment by davidem00** [comment]
it looks like the Markdown characters used by GitHub Issues is making the above stack trace fail to display completely.  You can see the actual stack trace text if you enter "edit" mode for the Issue Description above.
